# Create executables/builds/artifacts for C & C++ code
name: Create executables for C & C++ code

on:
  push:
    branches: [ "main", "develop", "stagging" ]
  pull_request:
    branches: [ "main", "develop", "stagging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
    - name: Run build command
      run: make

    - name: Setup SSH key
        run:|
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 65.0.173.200 >> ~/.ssh/known_hosts

    - name: Deploy to Server
        run:|
          ssh 65.0.173.200
   
